import { LegalPage } from "@/components/legal/LegalPage";

export const metadata = {
  title: "Terms of Service · Nexcor",
  description:
    "The rules of using Nexcor. Plain English. Read them, they matter.",
};

export default function TermsPage() {
  return (
    <LegalPage
      title="TERMS OF SERVICE"
      subtitle="Our rules. Short. Honest. Read them."
      lastUpdated="April 24, 2026"
      versionTag="NEXCOR TERMS · v.324B21"
    >
      <blockquote>
        These terms explain what you can do on Nexcor, what we promise, and what
        we don&apos;t. Skip the legalese &mdash; we wrote this so a real person can
        read it.
      </blockquote>

      <h2>Acceptance</h2>
      <p>
        By creating an account or using Nexcor, you agree to these Terms of
        Service and our Privacy Policy. If you don&apos;t agree with something, don&apos;t
        use Nexcor.
      </p>

      <h2>Eligibility</h2>
      <p>
        <strong>Nexcor is only for people 18 years of age or older.</strong> By
        creating an account, you confirm you are 18 or older. If we discover you
        are a minor, we will delete your account.
      </p>
      <p>
        You must also have the legal capacity to enter into contracts in your
        country.
      </p>

      <h2>Your account</h2>
      <ul>
        <li>You&apos;re responsible for keeping your password secure.</li>
        <li>You&apos;re responsible for everything that happens under your account.</li>
        <li>Don&apos;t share your account. Don&apos;t create an account on behalf of someone else.</li>
        <li>One real person per account. No bots, no mass automation, no scrapers.</li>
        <li>Usernames that impersonate others, mislead, or harass will be reclaimed.</li>
      </ul>

      <h2>Acceptable use</h2>
      <p>Using Nexcor, you agree NOT to:</p>
      <ul>
        <li>Create characters depicting <strong>minors in sexual contexts</strong> (this is a hard line with zero exceptions &mdash; doing so results in immediate account termination and may be reported to authorities).</li>
        <li>Create content designed to harass, threaten, or incite violence against real people.</li>
        <li>Impersonate real identifiable people (public figures included) in ways designed to deceive or harm.</li>
        <li>Generate or share content that is illegal in your jurisdiction.</li>
        <li>Attempt to jailbreak or exploit the AI to produce content that violates these terms.</li>
        <li>Extract, scrape, or re-publish other users&apos; private characters or conversations.</li>
        <li>Use Nexcor to generate spam, malware, phishing content, or misinformation.</li>
        <li>Reverse-engineer, decompile, or try to access our source code or infrastructure.</li>
        <li>Use automated tools to consume Marks or abuse the rate limits.</li>
        <li>Resell or commercialize Nexcor access without permission.</li>
      </ul>
      <p>
        Violations result in account termination. Severe violations (especially
        involving minors) may be reported to law enforcement.
      </p>

      <h2>Your content</h2>
      <p>
        When you create characters, send messages, or contribute anything to
        Nexcor, here&apos;s the deal:
      </p>
      <ul>
        <li><strong>You own what you create.</strong> The characters, the writing, your creative input &mdash; it&apos;s yours.</li>
        <li><strong>You grant us a license</strong> to host, store, display, and distribute your public content so Nexcor can function (for example: showing your public character in the Explore gallery, letting other users chat with it, generating AI responses based on it). This license is non-exclusive and royalty-free and only exists for running the platform.</li>
        <li><strong>When you delete content, the license ends.</strong> We will stop displaying it and remove it from active systems within 30 days.</li>
        <li><strong>You are responsible for your content.</strong> If you upload copyrighted material you don&apos;t own, harassing content, or anything that violates these terms, we&apos;ll remove it and may terminate your account.</li>
      </ul>

      <h2>AI-generated content disclaimer</h2>
      <p>
        AI characters on Nexcor are <strong>not real people</strong>. They
        cannot feel, love, or think, even if their responses sound like they do.
        Their replies are generated by statistical models and can be wrong,
        misleading, or offensive.
      </p>
      <p>
        <strong>Do not rely on AI characters for:</strong>
      </p>
      <ul>
        <li>Medical advice or mental health crisis support (please contact a qualified professional, or call an emergency number)</li>
        <li>Legal advice</li>
        <li>Financial or investment advice</li>
        <li>Relationship replacement or human connection in lieu of real support networks</li>
      </ul>
      <p>
        If you are struggling, please talk to someone real. We love that Nexcor
        brings you comfort, but it is not a substitute for human help.
      </p>

      <h2>Marks, payments, and refunds</h2>
      <h3>How Marks work</h3>
      <ul>
        <li>Marks are a virtual in-app currency required to send messages on Nexcor.</li>
        <li>All messages cost Marks. There are no free messages for non-subscribers. Current costs: Haiku 3 Marks, Sonnet 10 Marks, Opus 25 Marks per message.</li>
        <li>Active subscribers receive Haiku messages at no Mark cost and discounted rates on Sonnet and Opus as part of their subscription.</li>
        <li>Marks have <strong>no cash value</strong> and are not your property.</li>
        <li>Marks are not redeemable for money or transferable between accounts.</li>
        <li>We may adjust the Mark cost of messages in the future. If we make a significant negative change, we&apos;ll notify you in advance.</li>
        <li>Marks purchased via Mark Packs do not expire.</li>
        <li>Marks earned via daily login bonuses or (future) rewarded ads may expire if your account is inactive for 12+ months.</li>
      </ul>

      <h3>Payments</h3>
      <ul>
        <li>All payments are processed by <strong>Stripe</strong>. We do not see or store your card details.</li>
        <li>Prices shown are in USD unless stated otherwise. Local currency conversion and taxes may apply at checkout.</li>
        <li>For Mark Packs: purchase is final once payment completes and Marks are credited to your account.</li>
      </ul>

      <h3>Refunds</h3>
      <ul>
        <li>Mark Pack purchases are generally non-refundable once Marks are credited.</li>
        <li>If a payment succeeds but Marks are not credited due to a technical failure, contact us and we&apos;ll make it right.</li>
        <li>For EU consumers: you have a 14-day right of withdrawal under consumer protection law, subject to our obligation to deliver digital content immediately (which you waive by accepting these terms at purchase).</li>
      </ul>

      <h3>Subscriptions (future)</h3>
      <p>
        Subscriptions (when available) renew automatically at the end of each
        period. You can cancel anytime in Settings. Cancellation takes effect at
        the end of the current paid period &mdash; no partial refunds.
      </p>

      <h2>Rate limits &amp; fair use</h2>
      <p>
        We may impose reasonable rate limits to keep Nexcor sustainable. If you
        exceed these, you may be temporarily throttled or paused. Abusive
        patterns may result in account action.
      </p>

      <h2>Our intellectual property</h2>
      <p>
        The Nexcor name, DnaLogo, visual design, codebase, and all non-user
        content are our intellectual property. You may not copy, mirror, or
        rebrand Nexcor. You may link to us and write about us freely.
      </p>

      <h2>Suspension and termination</h2>
      <p>
        We may suspend or terminate your account if:
      </p>
      <ul>
        <li>You violate these terms.</li>
        <li>Your actions harm other users or the platform.</li>
        <li>We&apos;re legally required to.</li>
      </ul>
      <p>
        You may delete your account anytime in Settings. When you do, we remove
        your data per our Privacy Policy.
      </p>

      <h2>Service availability</h2>
      <p>
        We try hard to keep Nexcor online, but we can&apos;t promise it will always
        work. Outages happen. Features may change or be removed. When possible,
        we&apos;ll give you notice of major changes.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law:
      </p>
      <ul>
        <li>Nexcor is provided &quot;as is&quot; without warranties of any kind.</li>
        <li>We are not liable for any indirect, incidental, or consequential damages arising from your use of Nexcor.</li>
        <li>Our total liability to you for any claim is limited to the greater of: the amount you paid us in the past 12 months, or $50 USD.</li>
      </ul>
      <p>
        Some jurisdictions don&apos;t allow these limitations &mdash; in those places,
        our liability is limited to the maximum extent permitted by law.
      </p>

      <h2>Indemnification</h2>
      <p>
        You agree to cover our costs (reasonable legal fees and damages) if we
        get sued because of content you created, posted, or shared on Nexcor,
        or because you violated these terms.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        We may update these terms over time. When we make material changes,
        we&apos;ll notify you by email and update the &quot;Last updated&quot; date. Continued
        use after changes means you accept the new terms.
      </p>

      <h2>Governing law</h2>
      <p>
        These terms are governed by the laws of Georgia (country). Disputes
        will be resolved in courts located in Georgia, unless your local
        consumer protection law requires otherwise.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms?{" "}
        <a href="/contact">Contact us</a> — we read every message personally.
      </p>
    </LegalPage>
  );
}
